### ISSUE TITLE
visual-motion shows incorrect numbers, renders incorrectly

### ISSUE THREAD

**Issue by jgarvin** [Fanael/relative-line-numbers#6]
Two issues here:

1. When you move to a line that is wrapped both the number 0 and the number 1 will appear in the margin on the current line, as if it's trying to render two line number labels on the same line.

2. The line number label is still counting based on physical lines rather than logical, so when a line wraps once the label for that line will be two greater than the previous label rather than one.

**Comment by Fanael** [comment]
> When you move to a line that is wrapped both the number 0 and the number 1 will appear in the margin on the current line, as if it's trying to render two line number labels on the same line.

That's because relative-line-numbers call `vertical-motion` when there's no margin, then it adds the margin, which changes the line lengths, which in turns changes logical new line positions.

Frankly, recommending `vertical-motion` (and other function that use it, like `next-line`) is *the* mistake here. It's *dog slow*. It's hard to use correctly, as we need to set the margin to the right width first, and only then calculate the line numbers – but the margin width depends on the line numbers! And then there's `visual-line-mode` which complicates things even further… No. Just no. Don't even think about `vertical-motion`. It's a good idea in theory, but doesn't work in practice.

**Comment by Fanael** [comment]
See 64157db08b.

**Comment by jgarvin** [comment]
visual-line-mode unfortunately is the best way for me to work. So is there no way to get accurate line numbers then?

**Comment by Fanael** [comment]
No, unless you know something I don't, which very well may be the case; patches are welcome.
